steps:

- name: 'gcr.io/cloud-builders/npm'
  args: [ 'install', '--omit=dev' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/playground:amf', '-f', 'Dockerfile', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/playground:amf' ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'playground',
    '--image', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/playground:$COMMIT_SHA',
    '--project', 'zero65-test',
    '--region', 'asia-south1',
    '--platform', 'managed'
  ]
