name: Build and Commit

permissions:
  contents: write

on:
  workflow_call:
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64:
        required: true

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Set up Google Artifacts Registry Access
        run: | 
          if [ -n "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" ]; then
            echo "Google Application Credentials found with Secrets"
            echo "@zero65:registry=https://asia-south1-npm.pkg.dev/zero65/npm/" > ~/.npmrc
            mkdir -p ~/.config/gcloud
            echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > ~/.config/gcloud/application_default_credentials.json
            npm install -g google-artifactregistry-auth
            npx google-artifactregistry-auth
          fi
          
      - name: npm ci
        run: npm ci
      
      - name: npm run build
        run: npm run build
      
      - name: Commit and Push Changes
        run: |
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.ref_name }}
          git show-ref
          git remote -v
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "Zero65 Bot"
            git config user.email "google-cloud-build@zero65.in"
            # git checkout -b test origin/test
            git add .
            git commit -m "npm run build"
            git push origin HEAD:$(git show-ref)
          fi
